#!/usr/bin/env python
"""catalog — generate .claude/CATALOG.md, an on-demand inventory of this project's assets.

A mechanical generator (like build-hooks.py — a plain script in hooks/, NOT a hook and NOT a
skill). It scans the four asset layers under .claude/ — skills/, agents/, commands/, workflows/
— and rewrites the auto-generated block of .claude/CATALOG.md: one line per asset with a
one-line purpose and its path, grouped by layer.

CATALOG.md is *on-demand*: CLAUDE.md points to it by path, and it is read only when a full
inventory is needed. It is deliberately NOT auto-loaded into every session — skills and agents
already have their description: injected by the harness, so printing the catalog every session
would just duplicate that. The SessionStart hook below only WARNS if the file is stale.

Usage:
    python .claude/hooks/catalog.py                  # build: regenerate .claude/CATALOG.md
    python .claude/hooks/catalog.py --check          # exit 1 if CATALOG.md is stale
    python .claude/hooks/catalog.py --warn-if-stale  # SessionStart: warn, never fail
    python .claude/hooks/catalog.py --on-edit        # PostToolUse: rebuild iff an asset changed

CATALOG.md is generated per-tree and is NOT symlinked (its content differs per tree, like
settings.json). Project root is resolved from $CLAUDE_PROJECT_DIR (fallback: cwd). On
macOS/Linux invoke with `python3`.

Note: the small frontmatter parser below is duplicated from agent-finder/scripts/agents.py on
purpose. Importing across skill bundles would couple this generator to those bundles and break
their "lift one folder into another project" portability. The ~15 duplicated lines are cheaper
than that coupling — do not "DRY" them away.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

CATALOG_MARKER = "<!-- catalog: auto-generated by catalog.py — do not edit below -->"

HEADER = """# CAPABILITY CATALOG

> On-demand inventory of this project's `.claude/` assets — every skill, agent, command, and
> workflow with a one-line purpose. Skills and agents already auto-load into every session by
> their `description:`; this is a map for lookup, not a loader. Generated by
> `python .claude/hooks/catalog.py` (regenerate with `/reindex`) — do not edit below the marker.
"""

# Layers to scan: (heading, subdir). Skills are <dir>/SKILL.md; the rest are <dir>/*.md.
LAYERS = ("skills", "agents", "commands", "workflows")


def _force_utf8() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def project_root() -> Path:
    return Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())


def claude_dir() -> Path:
    return project_root() / ".claude"


def catalog_path() -> Path:
    return claude_dir() / "CATALOG.md"


def parse_frontmatter(text: str) -> dict[str, str]:
    """Minimal YAML-frontmatter parse: scalar `key: value` and folded `key: >`/`|` blocks."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return {}
    fm = lines[1:end]
    data: dict[str, str] = {}
    i = 0
    while i < len(fm):
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", fm[i])
        if not m:
            i += 1
            continue
        key, val = m.group(1), m.group(2).strip()
        if val in ("", ">", ">-", ">+", "|", "|-", "|+"):  # folded/literal/empty -> gather block
            block, j = [], i + 1
            while j < len(fm) and (fm[j].startswith((" ", "\t")) or fm[j].strip() == ""):
                block.append(fm[j].strip())
                j += 1
            data[key] = " ".join(b for b in block if b)
            i = j
        else:
            data[key] = val.strip().strip("\"'")
            i += 1
    return data


def first_body_line(text: str) -> str:
    """First meaningful line below the frontmatter (strip leading '#'), for files with no desc."""
    lines = text.splitlines()
    start = 0
    if lines and lines[0].strip() == "---":
        end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
        if end is not None:
            start = end + 1
    for line in lines[start:]:
        s = line.strip().lstrip("#").strip()
        if s:
            return s
    return ""


def one_line(text: str, limit: int = 100) -> str:
    """Collapse whitespace to one line and truncate at a word boundary (keeps the catalog scannable)."""
    s = " ".join((text or "").split())
    if not s:
        return "(no description)"
    if len(s) <= limit:
        return s
    return s[:limit].rsplit(" ", 1)[0] + " …"


def rel(path: Path) -> str:
    """Path shown relative to .claude/ (built from the unresolved path, so symlinks read naturally)."""
    try:
        return path.relative_to(claude_dir()).as_posix()
    except ValueError:
        return path.as_posix()


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def scan_skills() -> list[tuple[str, str, str]]:
    """skills/<name>/SKILL.md — name from `name:` (fallback folder), desc from `description:`."""
    base = claude_dir() / "skills"
    rows: list[tuple[str, str, str]] = []
    if not base.is_dir():
        return rows
    for entry in base.iterdir():  # is_dir()/is_file() follow symlinks — captures symlinked skill dirs
        skill_md = entry / "SKILL.md"
        if not skill_md.is_file():
            continue
        fm = parse_frontmatter(read(skill_md))
        name = fm.get("name") or entry.name
        rows.append((name, one_line(fm.get("description", "")), rel(skill_md)))
    return sorted(rows)


def scan_flat(subdir: str, name_from_frontmatter: bool) -> list[tuple[str, str, str]]:
    """A layer of <subdir>/*.md files (skip README.md). Used for agents/commands/workflows."""
    base = claude_dir() / subdir
    rows: list[tuple[str, str, str]] = []
    if not base.is_dir():
        return rows
    for path in base.glob("*.md"):  # glob follows symlinked .md entries (e.g. factory operational files)
        if path.name == "README.md":
            continue
        text = read(path)
        fm = parse_frontmatter(text)
        name = fm.get("name") if name_from_frontmatter else None
        name = name or path.stem
        desc = fm.get("description") or first_body_line(text)
        rows.append((name, one_line(desc), rel(path)))
    return sorted(rows)


def build_catalog_body() -> str:
    sections = [
        ("Skills", "skills/*/SKILL.md", scan_skills()),
        ("Agents", "agents/*.md", scan_flat("agents", name_from_frontmatter=True)),
        ("Commands", "commands/*.md", scan_flat("commands", name_from_frontmatter=False)),
        ("Workflows", "workflows/*.md", scan_flat("workflows", name_from_frontmatter=False)),
    ]
    out: list[str] = []
    for title, glob, rows in sections:
        out.append(f"## {title} ({glob})")
        if rows:
            out.extend(f"- {name} — {desc} -> {path}" for name, desc, path in rows)
        else:
            out.append("- (none)")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def render() -> str:
    """Preamble (preserved above the marker if present) + marker + freshly-scanned catalog."""
    preamble = HEADER
    if catalog_path().exists():
        existing = read(catalog_path())
        if CATALOG_MARKER in existing:
            preamble = existing.split(CATALOG_MARKER)[0]
    return preamble.rstrip("\n") + "\n\n" + CATALOG_MARKER + "\n\n" + build_catalog_body()


def current_text() -> str:
    return read(catalog_path()) if catalog_path().exists() else ""


def is_catalog_source(file_path: str | None) -> bool:
    """True if file_path is one of the asset files the catalog is built from.

    Uses OS file identity (samefile) rather than string equality, so it is robust to path-format
    differences AND to the symlink boundary in the factory tree (the harness reports the symlink
    path; samefile resolves it to the same canonical inode).
    """
    if not file_path:
        return False
    try:
        p = Path(file_path)
        if p.suffix != ".md" or p.name == "README.md":
            return False
        cd = claude_dir()
        if p.name == "SKILL.md":
            return _samefile(p.parent.parent, cd / "skills")
        return any(_samefile(p.parent, cd / layer) for layer in ("agents", "commands", "workflows"))
    except (OSError, ValueError):
        return False


def _samefile(a: Path, b: Path) -> bool:
    try:
        return a.exists() and b.exists() and os.path.samefile(a, b)
    except (OSError, ValueError):
        return False


def read_stdin_json() -> dict:
    try:
        data = sys.stdin.read()
        return json.loads(data) if data.strip() else {}
    except (ValueError, TypeError, OSError):
        return {}


# --- modes -----------------------------------------------------------------

def mode_build() -> int:
    catalog_path().write_text(render(), encoding="utf-8")
    print(f"wrote {rel(catalog_path())}")
    return 0


def mode_check() -> int:
    if current_text() != render():
        print("stale: .claude/CATALOG.md does not match the assets. Run catalog.py.")
        return 1
    print("ok: .claude/CATALOG.md is in sync with the assets")
    return 0


def mode_warn_if_stale() -> int:
    """SessionStart: surface drift into context, but never block the session."""
    if current_text() != render():
        print("WARNING: .claude/CATALOG.md is out of sync with the assets in .claude/. "
              "Run `/reindex` (or `python .claude/hooks/catalog.py`) to regenerate it.")
    return 0


def mode_on_edit() -> int:
    """PostToolUse: if the edited file was a catalog source, regenerate CATALOG.md."""
    payload = read_stdin_json()
    file_path = (payload.get("tool_input") or {}).get("file_path")
    if not is_catalog_source(file_path):
        return 0
    catalog_path().write_text(render(), encoding="utf-8")
    print(f"rebuilt .claude/CATALOG.md ({Path(file_path).name} changed)")
    return 0


def main(argv: list[str] | None = None) -> int:
    _force_utf8()
    parser = argparse.ArgumentParser(prog="catalog.py")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true",
                       help="verify CATALOG.md matches the assets; exit 1 if stale")
    group.add_argument("--warn-if-stale", action="store_true",
                       help="SessionStart hook: print a warning if stale, always exit 0")
    group.add_argument("--on-edit", action="store_true",
                       help="PostToolUse hook: rebuild iff the edited file is a catalog source")
    args = parser.parse_args(argv)

    if args.check:
        return mode_check()
    if args.warn_if_stale:
        return mode_warn_if_stale()
    if args.on_edit:
        return mode_on_edit()
    return mode_build()


if __name__ == "__main__":
    raise SystemExit(main())
