#!/usr/bin/env python3
"""Manage the .claude/context/ reference-notes tier. Stdlib only.

Holds durable, non-path-scoped declarative reference (concepts, domain facts, system
maps, schemas, rationale). NOT evolving state (that's .claude/memory/), NOT procedures
(those become skills), NOT code-scoped conventions (keep those in CLAUDE.md).

Subcommands:
  new --slug S [--title T] [--type TYPE]   Create notes/<slug>.md from template, reindex.
  list                                     List notes with their titles.
  search QUERY [--limit N]                 Grep across INDEX.md and all notes.
  reindex                                  Rebuild INDEX.md's catalog from the notes.
  index                                    Print INDEX.md to stdout (SessionStart hook).

INDEX.md is the always-loaded discovery surface (one line per note); the notes are read
on demand. `reindex` regenerates the catalog mechanically so the index can't drift from
the notes — run it after adding or removing a note (new does it for you).
"""
from __future__ import annotations

import argparse
import datetime as _dt
import os
import re
import sys
from pathlib import Path

CATALOG_MARKER = "<!-- catalog: auto-generated by context.py reindex — do not edit below -->"
HEADER = ("# CONTEXT INDEX  ·  reference notes\n\n"
          "> Always-loaded discovery surface. Each note below is read on demand when its\n"
          "> topic is relevant. Durable reference only — state lives in .claude/memory/.\n\n")

TEMPLATE = """# {title}
type: {type}
status: current

## What it is
{summary}

## Key points
-

## Where it shows up / pointers
<!-- files, systems, external docs this concept touches -->
-

## Source
- {source}
"""

KEY_RE = re.compile(r"^([A-Za-z][\w-]*):\s?(.*)$")


def base_dir() -> Path:
    root = os.environ.get("CLAUDE_PROJECT_DIR")
    if root:
        return Path(root)
    cur = Path.cwd().resolve()
    for p in [cur, *cur.parents]:
        if (p / ".git").exists():
            return p
    return cur


def context_dir() -> Path:
    return base_dir() / ".claude" / "context"


def notes_dir() -> Path:
    return context_dir() / "notes"


def index_path() -> Path:
    return context_dir() / "INDEX.md"


def slugify(text: str) -> str:
    text = re.sub(r"[^a-z0-9]+", "-", text.strip().lower())
    return re.sub(r"-{2,}", "-", text).strip("-") or "note"


def note_meta(path: Path) -> tuple[str, str]:
    """Return (title, type) from a note's H1 and `type:` line."""
    title, ntype = path.stem, "reference"
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# ") and title == path.stem:
                title = line[2:].strip()
            m = KEY_RE.match(line)
            if m and m.group(1) == "type":
                ntype = m.group(2).strip() or ntype
    except OSError:
        pass
    return title, ntype


def reindex() -> int:
    nd = notes_dir()
    notes = sorted(nd.glob("*.md")) if nd.exists() else []
    lines = [CATALOG_MARKER, ""]
    if not notes:
        lines.append("- (no notes yet)")
    for f in notes:
        title, ntype = note_meta(f)
        lines.append(f"- {title} [{ntype}] -> notes/{f.name}")
    catalog = "\n".join(lines) + "\n"

    idx = index_path()
    idx.parent.mkdir(parents=True, exist_ok=True)
    preamble = HEADER
    if idx.exists():
        existing = idx.read_text(encoding="utf-8")
        if CATALOG_MARKER in existing:
            preamble = existing.split(CATALOG_MARKER)[0]
    idx.write_text(preamble.rstrip("\n") + "\n\n" + catalog, encoding="utf-8")
    return len(notes)


def cmd_new(args: argparse.Namespace) -> int:
    nd = notes_dir()
    nd.mkdir(parents=True, exist_ok=True)
    title = args.title or (args.slug.replace("-", " ") if args.slug else "untitled")
    slug = slugify(args.slug or title)
    path = nd / f"{slug}.md"
    if path.exists():
        print(f"note already exists: {path}", file=sys.stderr)
        return 1
    path.write_text(TEMPLATE.format(
        title=title, type=args.type,
        summary="", source=_dt.datetime.now().strftime("%Y-%m-%d")), encoding="utf-8")
    n = reindex()
    print(f"{path}\n(reindexed: {n} note(s))")
    return 0


def cmd_list(_: argparse.Namespace) -> int:
    nd = notes_dir()
    if not nd.exists() or not any(nd.glob("*.md")):
        print("(no notes yet)")
        return 0
    for f in sorted(nd.glob("*.md")):
        title, ntype = note_meta(f)
        print(f"  {f.name:<32} [{ntype}]  {title}")
    return 0


def cmd_search(args: argparse.Namespace) -> int:
    cd = context_dir()
    if not cd.exists():
        print("(no context dir yet)", file=sys.stderr)
        return 0
    pat = re.compile(re.escape(args.query), re.IGNORECASE)
    targets = []
    if index_path().exists():
        targets.append(index_path())
    targets.extend(sorted(notes_dir().glob("*.md")) if notes_dir().exists() else [])
    hits = 0
    for f in targets:
        try:
            for i, line in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
                if pat.search(line):
                    print(f"{f.relative_to(cd.parent)}:{i}: {line.strip()}")
                    hits += 1
                    if args.limit and hits >= args.limit:
                        return 0
        except OSError:
            continue
    if hits == 0:
        print("(no matches)", file=sys.stderr)
    return 0


def cmd_reindex(_: argparse.Namespace) -> int:
    n = reindex()
    print(f"reindexed {n} note(s) into {index_path()}")
    return 0


def cmd_index(_: argparse.Namespace) -> int:
    """SessionStart: print INDEX so it loads into context. Silent if absent."""
    if index_path().exists():
        sys.stdout.write(index_path().read_text(encoding="utf-8", errors="replace"))
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Reference-notes manager")
    sub = p.add_subparsers(dest="cmd", required=True)

    n = sub.add_parser("new", help="create a reference note")
    n.add_argument("--slug", default="")
    n.add_argument("--title", default="")
    n.add_argument("--type", default="reference",
                   help="concept | domain-fact | system-map | schema | rationale | glossary | lesson")
    n.set_defaults(func=cmd_new)

    sub.add_parser("list", help="list notes").set_defaults(func=cmd_list)

    s = sub.add_parser("search", help="grep notes + index")
    s.add_argument("query")
    s.add_argument("--limit", type=int, default=0)
    s.set_defaults(func=cmd_search)

    sub.add_parser("reindex", help="rebuild the index catalog").set_defaults(func=cmd_reindex)

    sub.add_parser("index", help="print INDEX.md to stdout (SessionStart hook)").set_defaults(func=cmd_index)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
